name: Build CI

on:
  push:
  pull_request:
  schedule:
    # build the main branch every Monday morning
    - cron: '17 5 * * 1'

jobs:
  build-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [cc, clang-9, gcc-10]
    steps:
      - uses: actions/checkout@v2
      - name: autogen
        run: ./autogen.sh
      - name: compiler
        run: $CC -v
        env:
          CC: ${{ matrix.compiler }}
      - name: libtls
        run: ./build_libtls.sh
      - name: configure
        run: ./configure
        env:
          CC: ${{ matrix.compiler }}
      - name: make
        run: make -k
      - name: make distcheck
        run: make distcheck
        if: matrix.compiler == 'cc'
      - name: test run
        run: mkdir rpki-cache rpki; src/rpki-client -v -t afrinic.tal -t apnic.tal -t lacnic.tal -t ripe.tal -d rpki-cache rpki
        if: matrix.compiler == 'cc'
      - name: test run rrdp single ta
        run: mkdir rpki-cache-rrdp-1ta rpki-rrdp-1ta; src/rpki-client -r -v -t afrinic.tal -d rpki-cache-rrdp-1ta rpki-rrdp-1ta
        if: matrix.compiler == 'cc'
      - name: test run rrdp
        run: mkdir rpki-cache-rrdp rpki-rrdp; src/rpki-client -r -v -t afrinic.tal -t apnic.tal -t lacnic.tal -t ripe.tal -d rpki-cache-rrdp rpki-rrdp
        if: matrix.compiler == 'cc'
